version: '3'
services:
  # web:
  #   build: .
  #   ports:
  #   - "8080:8080"
  #   - "4200:4200"
  #   - "3000:3000"
  #   depends_on:
  #   - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"